server:
  port: 8082

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.code.test.dao
  mapper-locations:
    - mapper/*