# 当前环境（dev/test），可以通过 -Denv=dev 或 -Denv=test 来切换
env=test

# 各环境对应的基础 URL
dev.url=http://localhost:8083
test.url=http://localhost:8082

# moco 服务地址（大多场景下保持一致）
dev.moco.url=http://localhost:8888
test.moco.url=http://localhost:8888

login.uri=/v1/login
addUser.uri=/v1/addUser
getUserInfo.uri=/v1/getUserInfo
getUserList.uri=/v1/getUserLis
updateUser.uri=/v1/updateUser
moco.login.uri=/post/login
moco.get.uri=/getdemo/api1/getTest
moco.post.uri=/postwithToken/urlencoded