api.base.url=http://localhost:8080/api
db.url=jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=UTC
db.username=root
db.password=password
db.driver=com.mysql.cj.jdbc.Driver

# ????
crypto.aes.key=1234567890123456
crypto.rsa.publicKey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCt748/LfKzpl99jnX2dndUermuLhNri0pEGU4TrrFAYOb2kl37WN5VaCVt9EyaepDqiouRe1M/ejh9zOUS3Lkk4IZiHhkfeP6EH6za+9PozQIVjkICUf4qb0sRYaIAlwF13HXtKzGgk9Qj1eH/2A6WT4Fpis6ODZkhjC7EG+DlzwIDAQAB
crypto.app.secret=my_super_secret_key