server:
  port: 8083

logging:
  path: logs
  file: userManager.log
spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
    username: root
    password: 123456
  http:
    multipart:
      max-file-size: 100000
      max-request-size: 100000

mybatis:
  type-aliases-package: com.course.code.model
  mapper-locations:
    - mapper/*